### ISSUE TITLE
[FE] MainLayout 컴포넌트 생성

### ISSUE THREAD

**Issue by aken-you** [aken-you/second-hand-refactor-fe#2]
## ☑️ 진행할 작업

Header는 상단, TabBar(또는 ToolBar)는 하단에 항상 고정이기 때문에 main content의 height를 브라우저 높이에서 상단과 하단의 height를 제외한 길이로 설정하려고 한다.

## 📝TODO

- [x] MainLayout 컴포넌트 생성
- [x] Home 페이지에 적용
- [x] Category 페이지에 적용
- [x] CategoryDetail 페이지에 적용
